name: macOS Ventura Build Tools

on: [pull_request]

jobs:
  macos-ventura-ci:
    runs-on: macos-13
    name: macOS Ventura Build Tools
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Build Tools
        run: |
          python3 -m venv /Users/runner/venv
          source /Users/runner/venv/bin/activate
          python3 -m pip install vcstool
          python3 -m pip install colcon-common-extensions

      - name: Check Build Tools
        run: |
          source /Users/runner/venv/bin/activate
          which pip3
          which python3
          python3 --version
          colcon graph
